steps:
  - name: 'python:3.10'
    id: Install and Trace
    entrypoint: bash
    args:
      - -c
      - |
        pip install -r requirements.txt
        python otel_trace.py

timeout: 900s

options:
  logging: CLOUD_LOGGING_ONLY
